config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'top#index'

  resources :top, only: [:index]
  resources :topics do
    resources :netas, only: %i[new create]
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
    resource  :headerimage, only: %i[destroy], module: 'topics'
  end

  resources :netas, only: %i[show edit update destroy] do
    resources :trades, only: %i[new create]
    resources :reviews, only: [:create]
    resources :bookmarks, only: %i[create destroy]
  end

  match '/trades/webhook' => 'trades#webhook', :via => %i[get post]

  namespace :hashtags do
    resources :netas, only: [:index]
    resources :autocomplete, only: [:index]
  end

  resources :comments, only: [:show] do
    resources :likes, only: %i[create destroy]
  end

  resources :copychecks, only: %i[new create show update index]
  resources :inquiries, only: %i[new create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i[show edit update] do
    resources :followers, only: %i[create destroy index]
    resources :followings, only: [:index]
    resources :violations, only: %i[new create]
    resources :accounts, module: 'business', only: %i[new create] do
      post :confirm, on: :collection
    end
    resource :avatar, only: [:destroy], module: 'users'
  end

  scope module: :business do
    resources :accounts, only: %i[show edit update destroy] do
      patch :confirm, on: :member
      resources :payouts, only: %i[new create]
      resources :idcards, only: %i[new create]
      resource  :extacct, only: %i[new create edit update]
    end
    resources :idcards, only: [:destroy]
    resources :bank_autocomplete, only: [:index]
    resources :branch_autocomplete, only: [:index]
  end

  resources :emailrecs, only: %i[index show]
  resource :policy, only: [:show]
  resource :userterm, only: [:show]
  resource :tokutei, only: [:show]
end

app/models/topic.rb
# frozen_string_literal: true

class Topic < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  has_many      :netas, dependent: :restrict_with_error
  has_many      :pageviews, as: :pageviewable, dependent: :destroy
  has_many      :bookmarks, as: :bookmarkable, dependent: :destroy
  has_many      :comments,  as: :commentable, dependent: :destroy
  has_many      :likes,     as: :likeable, dependent: :destroy
  validates     :title,     presence: true, uniqueness: { case_sensitive: true }, length: { maximum: 35 }
  validates     :netas_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates     :pageviews_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates     :likes_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates     :bookmarks_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates     :comments_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate      :content_check
  validate      :header_url_check

  def max_rate
    maxrate = 0
    netas.each do |neta|
      rate = neta.average_rate
      maxrate = rate if rate != 0 && rate > maxrate
    end
    maxrate
  end

  def owner(user)
    user_id == user.id
  end

  def editable(user)
    editable = true
    if owner(user)
      netas.each do |neta|
        editable = false if neta.user_id != user.id
      end
    else
      editable = false
    end
    editable
  end

  def bookmarked(user_id)
    bookmark = bookmarks.find_by(user_id: user_id)
    bookmark.present?
  end

  def add_pageview(user)
    from = 1.day.ago
    to = Time.zone.now
    pageviews.find_or_create_by(user_id: user.id, created_at: from..to)
  end

  def deleteable
    netas.blank?
  end

  def purge_s3_object
    if header_url_check
      object = S3_BUCKET.object(header_img_url.split('amazonaws.com/')[1])
      if object.present?
        object.delete
        true
      else
        false
      end
    else
      errors.blank?
    end
  end

  private

  def content_check
    errors.add(:content, I18n.t('errors.messages.blank')) if content.body.blank?
    errors.add(:content, I18n.t('errors.messages.too_long', count: '300')) if content.to_plain_text.squish.length > 300
    # Need attachment checks. Below does not work because at this point blob is not attached.
    # self.content.embeds.blobs.each do |blob|
    #   if blob.byte_size.to_i > 5.megabytes
    #     errors.add(:content, " size must be smaller than 5MB")
    #   end
    # end
  end

  def header_url_check
    if header_img_url.present?
      if header_img_url.include?('amazonaws.com/')
        path = header_img_url.split('amazonaws.com/')[1]
        if path.include?('topic_header_images')
          true
        else
          errors.add(:header_img_url, I18n.t('errors.messages.invalid'))
          false
        end
      else
        errors.add(:header_img_url, I18n.t('errors.messages.invalid'))
        false
      end
    else
      false
    end
  end
end

app/controllers/topics/headerimages_controller.rb
# frozen_string_literal: true

class Topics::HeaderimagesController < ApplicationController
  def destroy
    @topic = Topic.find(params[:topic_id])
    if @topic.present?
      if @topic.header_img_url.present?
        @topic.header_img_url = nil
        @topic.save!
      else
        logger.error "topic.header_img_url is blank. Topic ID : #{@topic.id}"
      end
      redirect_to edit_topic_path(@topic.id) and return
    else
      redirect_to topics_path and return
    end
  end
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_s3_direct_post, only: %i[new edit]

  def index
    @search = Topic.includes(:user, :netas).where(private_flag: false).ransack(params[:q])
    @topic_cards = @search.result(distinct: true).order('created_at DESC').page(params[:page]).per(20)
    @hashtag_ranking = Hashtag.get_ranking(10)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(post_params)
    if @topic.save
      redirect_to topics_path, notice: I18n.t('controller.topic.created') and return
    else
      render :new and return
    end
  end

  def show
    @topic = Topic.includes(:user).find(params[:id])
    @owner = owner(@topic)
    if @topic.private_flag && !@owner
      @message = I18n.t('controller.topic.private')
    else
      @netas = @topic.netas.includes(:user).where(private_flag: false).order('average_rate DESC')
      @comments = @topic.comments.includes(:user).order('created_at ASC')
      if user_signed_in?
        @newcomment = Comment.new
        @topic.add_pageview(current_user)
      end
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    redirect_to topic_path(@topic.id), alert: I18n.t('controller.general.no_access') and return unless owner(@topic)
  end

  def update
    @topic = Topic.find(params[:id])
    if owner(@topic)
      @topic.purge_s3_object if post_params[:header_img_url].present?
      if @topic.update(post_params)
        redirect_to topic_path(@topic.id), notice: I18n.t('controller.topic.updated') and return
      else
        render :edit and return
      end
    else
      redirect_to topic_path(@topic.id), alert: I18n.t('controller.general.no_access') and return
    end
  end

  def destroy
    @topic = Topic.includes(:netas, :pageviews, :bookmarks).find(params[:id])
    if deleteable
      if @topic.destroy
        redirect_to topics_path, notice: I18n.t('controller.topic.deleted') and return
      else
        render :edit and return
      end
    else
      redirect_to topic_path(@topic.id), alert: @message and return
    end
  end

  private

  def post_params
    params.require(:topic).permit(:title, :content, :header_img_url, :private_flag).merge(user_id: current_user.id)
  end

  def owner(topic)
    if user_signed_in?
      topic.owner(current_user)
    else
      false
    end
  end

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "topic_header_images/#{SecureRandom.uuid}/${filename}",
                                               success_action_status: '201', acl: 'public-read')
  end

  def deleteable
    if owner(@topic)
      if @topic.deleteable
        @topic.purge_s3_object
        true
      else
        @message = I18n.t('controller.topic.has_child')
        false
      end
    else
      @message = I18n.t('controller.general.no_access')
      false
    end
  end
end

app/views/topics/_errorform.html.erb
<div class="error-message">
  <ul>
    <% @topic.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/topics/_topic.html.erb
<% if @topic.header_img_url.present? %>
  <%= image_tag @topic.header_img_url, :class => 'topic__header-image' %>
<% end %>
<h1 class="topic__title"><%= @topic.title %></h1>
<div class="topic__text">
  <%= @topic.content %>
  <% if user_signed_in? %> 
    <% if @topic.editable(current_user) %>
      <%= link_to '編集', edit_topic_path(@topic.id) %>
    <% end %>
  <% end %>
</div>
<div class="topic__footer">
  <%= link_to user_path(@topic.user_id) do %>
    <% if @topic.user.avatar_img_url.present? %>
      <%= image_tag @topic.user.avatar_img_url, {:class => "topic__author-image"} %>
    <% else %>
      <%= image_bundle_tag "no_user_image.png", {:class => "topic__author-image"} %>
    <% end %>
  <% end %>
  <span class="topic__footer-text">
    <%= @topic.user.nickname %>&nbsp;&nbsp;
    <%= @topic.created_at.to_s(:human) %>&nbsp;&nbsp;
  </span>
  <div class="topic__footer-icons">
    <% if (user_signed_in? && @owner == false) %>
      <span id="likes_buttons_<%= @topic.class.name.downcase %>_<%= @topic.id %>">
        <%= render partial: 'likes/like', locals: { likeable: @topic } %>
      </span>
      <span id="bookmark_buttons_<%= @topic.class.name.downcase %>_<%= @topic.id %>">
        <%= render partial: 'bookmarks/bookmark', locals: { bookmarkable: @topic } %>
      </span>
    <% else %>
      <i class="like-large--inactive material-icons">favorite_border</i>
      <span class="like__count--inactive"><%= @topic.likes_count %></span>&nbsp;&nbsp;
      <i class="bookmark-large--inactive material-icons">bookmark_border</i>
    <% end %>
  </div>
</div>

app/views/topics/_topic_card.html.erb
<%= link_to topic_path(topic_card.id) do %>
  <div class="topics-index card">
    <div class="topics-index card-image">
      <% if topic_card.header_img_url.present? %>
        <%= image_tag topic_card.header_img_url %>
      <% else %>
        <%= image_bundle_tag "teppan_gray.jpeg" %>
      <% end %>
    </div>
    <div class="topics-index card-content">
      <div class="topics-index__title"><%= truncate(topic_card.title, length: 12) %></div>
      <div class="topics-index__postdata">
        <% if topic_card.max_rate == 0 %>
          <span class="js-topics-index__star" rating-data="0"></span>
        <% else %>
          <span class="js-topics-index__star" rating-data="<%= topic_card.max_rate %>"></span>
          <span class="topics-index__star-count"><%= format("%.2f", topic_card.max_rate) %></span>
        <% end %>
        <i class="topics-index__neta-icon material-icons">create</i>
        <span class="topics-index__icon-count"><%= topic_card.netas_count %></span>
      </div>
      <div class="topics-index__author">
        <%= link_to user_path(topic_card.user_id) do %>
          <% if topic_card.user.avatar_img_url.present? %>
            <%= image_tag topic_card.user.avatar_img_url, {:class => "topics-index__author-image"} %>
          <% else %>
            <%= image_bundle_tag "no_user_image.png", {:class => "topics-index__author-image"} %>
          <% end %>
          <span class="topics-index__author-name"><%= topic_card.user.nickname %></span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/topics/_topicform.html.erb
<div class="topic-form__header-img">
  <div class = "topic-form__header-img-label">ヘッダー画像</div>
  <%= form.label :header_image do %>
    <% if @topic.id.present? %>
      <% if @topic.header_img_url.present? %>
        <%= image_tag @topic.header_img_url, :class => 'topic-form__header-img-content' %><br>
        <span class="topic-form__header-img-deletelink">
          <%= link_to "画像を削除", topic_headerimage_path(@topic.id), :method => :delete %>
        </span><br>
      <% else %>
        <%= form.file_field :header_img_url, :class => 'js-topic-form__header-img-filefield' %>
        <div class="topic-form__header-img-wrapper">
          <canvas id="js-topic-header-canvas" class="topic-form__header-img-preview" />
        </div>
      <% end %>
    <% else %>
      <%= form.file_field :header_img_url, :class => 'js-topic-form__header-img-filefield' %>
      <div class="topic-form__header-img-wrapper">
        <canvas id="js-topic-header-canvas" class="topic-form__header-img-preview" />
      </div>
    <% end %>
  <% end %>
</div>
<div class="topic-form__title">
  <%= form.label :title, "テーマ・お題", :class => "topic-form__title-label" %>
  <%= form.text_field :title, :maxlength => '35', :class => "topic-form__title-text" %>
</div>
<div class="topic-form__content">
  <%= form.label :content, "本文", :class => "topic-form__content-label" %>
  <%= form.rich_text_area :content, :class => "topic-form__content-textarea"  %>
</div>
<div class="topic-form__private">
  <%= form.label :private_flag, "公開／非公開", :class => "topic-form__private-label"  %>
  <%= form.select :private_flag, [['公開', false], ['非公開', true]], { include_blank: false, selected: @topic.private_flag }, { class: "browser-default", :id => "topic-form__private-flag" } %>
</div>

app/views/topics/edit.html.erb
<%= javascript_bundle_tag 'topic' %>
<% @page_title = @topic.title + "（編集）" %>
<% breadcrumb :edit_topic, @topic %>
<div class="page-body">
  <div class="row">
    <div class="col s12 m12 topic">
      <div class="row content-header">
        <%= render partial: "layouts/breadcrumbs" %>
      </div>
      <div class="row topic-edit">
        <h1>トピック編集</h1>
        <% if @s3_direct_post.present? %>
          <%= form_with model: @topic, local: true, class: 'topic-form__form', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } do |form| %>
            <% if @topic.errors.any? %>
              <%= render :partial => "errorform" %>
            <% end %>
            <%= render :partial => "topicform", locals: { form: form } %>
            <%= button_tag :type => "submit", class: "topic-edit__submit btn waves-effect" do %>
              <i class="topic-edit__submit material-icons left">refresh</i>更新
            <% end %>
            <%= link_to topic_path(@topic.id), {:method => :delete, :class => 'topic-edit__submit btn waves-effect', data: { confirm: "本当にトピックを削除しますか？" }} do %>
              <i class="topic-edit__submit material-icons left">delete</i>
              <span>削除</span>
            <% end %>
          <% end %>
        <% else %>
          <%= form_with model: @topic, local: true, class: 'topic-form__form' do |form| %>
            <% if @topic.errors.any? %>
              <%= render :partial => "errorform" %>
            <% end %>
            <%= render :partial => "topicform", locals: { form: form } %>
            <%= button_tag :type => "submit", class: "topic-edit__submit btn waves-effect" do %>
              <i class="topic-edit__submit material-icons left">refresh</i>更新
            <% end %>
            <%= link_to topic_path(@topic.id), {:method => :delete, :class => 'topic-edit__submit btn waves-effect', data: { confirm: "本当にトピックを削除しますか？" }} do %>
              <i class="topic-edit__submit material-icons left">delete</i>
              <span>削除</span>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<% @page_title = "トピック一覧" %>
<% breadcrumb :topics %>
<div class="page-body">
  <div class="row">
    <div class="col s12 m12 topics">
      <div class="row topics-pageheader">
        <div class="col s6 m6 topics-breadcrumbs">
          <%= breadcrumbs separator: "  &rsaquo;  ", :class => "breadcrumbs-tp" %>
        </div>
        <div class="col s6 m6 topics-search">
          <%= search_form_for(@search, url: topics_path, html: {method: :get, :class => 'topics-search__form', role: 'form'}) do |f| %>
            <%= f.text_field :title_or_netas_title_or_user_nickname_cont, :class => 'topics-search__input', :placeholder => 'キーワード検索', :autocomplete => 'off' %>
            <i class="topics-search__icon material-icons">search</i>
          <% end %>
        </div>
      </div>
      <div class="row topics-index">
        <%= render partial: "topics/topic_card", collection: @topic_cards %>
      </div>
      <div class="row topics-pagination">
        <%= paginate(@topic_cards) %>
      </div>
      <div class="row topics-trend">
        <h2>トレンド</h2>
        <% @hashtag_ranking.each do |key, value| %>
          <div class="topics-trend__hashtag"><%= link_to "#"+value[1], "/hashtags/netas?keyword=#{value[1]}" %></div>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <%= link_to new_topic_path, {:class => 'topics-new btn-floating'} do %>
          <i class="topics-new__icon material-icons">create</i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<%= javascript_bundle_tag 'topic' %>
<% @page_title = "新規トピック" %>
<% breadcrumb :new_topic %>
<div class="page-body">
  <div class="row">
    <div class="col s12 m12 content">
      <div class="row content-header">
        <%= render partial: "layouts/breadcrumbs" %>
      </div>
      <div class="row topic-new">
        <h1>新規トピック</h1>
        <% if @s3_direct_post.present? %>
          <%= form_with model: @topic, local: true, class: 'topic-form__form', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } do |form| %>
            <% if @topic.errors.any? %>
              <%= render :partial => "topics/errorform" %>
            <% end %>
            <%= render :partial => "topicform", locals: { form: form } %>
            <%= button_tag :type => "submit", class: "topic-new__submit btn waves-effect" do %>
              <i class="topic-new__submit material-icons left">create</i>投稿
            <% end %>
          <% end %>
        <% else %>
          <%= form_with model: @topic, local: true, class: 'topic-form__form' do |form| %>
            <% if @topic.errors.any? %>
              <%= render :partial => "topics/errorform" %>
            <% end %>
            <%= render :partial => "topicform", locals: { form: form } %>
            <%= button_tag :type => "submit", class: "topic-new__submit btn waves-effect" do %>
              <i class="topic-new__submit material-icons left">create</i>投稿
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<%= javascript_bundle_tag 'topic' %>
<% @page_title = @topic.title %>
<% @page_description = @topic.content.to_plain_text.squish.truncate(120) %>
<%= content_for(:ogp_article) do %>
  <meta property="og:type" content="article">
  <meta property="og:image" content="<%= @topic.header_img_url %>">
<% end %>
<% content_for(:twitter_card) do %>
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="<%= page_title %>">
  <meta name="twitter:description" content="<%= page_description %>">
  <meta name="twitter:image" content="<%= @topic.header_img_url %>">
  <meta name="twitter:url" content="<%= request.url %>"> 
<% end %>
<% breadcrumb :show_topic, @topic %>
<div class="page-body">
  <div class="row">
    <div class="col s12 m12 content">
      <% if @topic.private_flag && @owner == false %>
        <%= @message %>
      <% else %>
        <div class="row content-header">
          <%= render partial: "layouts/breadcrumbs" %>
        </div>  
        <div class="row topic-body">
          <%= render partial: "topics/topic" %>
        </div>
        <div class="row topic-tabs">
          <div class="topic-tab__menu">
            <ul class="topic-tab__menu-list collection">
              <li class="js-topic-tab__link">投稿</li>
              <li class="js-topic-tab__link">コメント</li>
            </ul>
          </div>
          <div class="topic-tab__contents">
            <div class="js-topic-tab__body">
              <h2 class="topic-tab__title">投稿ネタ(<%= @netas.count %>件)</h2>
              <% if @netas %>
                <ul class="topic-tab__netas collection">
                  <%= render partial: "netas/neta", :collection => @netas %>
                </ul>
              <% else %>
                <p class="topic-tab__nodata"> (投稿はありません) </p>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to new_topic_neta_path(@topic.id), {:class => 'topic-tab__neta-new'} do %>
                  <i class="topic-tab__neta-new material-icons">create</i>
                <% end %>
              <% end %>
            </div>
            <div class="js-topic-tab__body">
              <h2 class="topic-tab__title">トピックへコメント(<%= @comments.count %>件)</h2>
              <% if @comments.present? %>
                <ul class="topic-tab__comments collection">
                  <%= render partial: "comments/comment", :collection => @comments %>
                </ul>
              <% else %>
                <p class="topic-tab__nodata">(コメントはありません) </p>
              <% end %>
              <% if user_signed_in? %>
                <ul class="topic-tab__comments collection">
                  <%= render partial: "comments/commentform", locals: { commentable: @topic, newcomment: @newcomment } %>
                </ul>
              <% end %>
            </div>
          </div>  
        </div>
      <% end %>
    </div>  
  </div>
</div>