config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'top#index'

  resources :top, only: [:index]
  resources :topics do
    resources :netas, only: %i[new create]
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
    resource  :headerimage, only: %i[destroy], module: 'topics'
  end

  resources :netas, only: %i[show edit update destroy] do
    resources :trades, only: %i[new create]
    resources :reviews, only: [:create]
    resources :bookmarks, only: %i[create destroy]
  end

  match '/trades/webhook' => 'trades#webhook', :via => %i[get post]

  namespace :hashtags do
    resources :netas, only: [:index]
    resources :autocomplete, only: [:index]
  end

  resources :comments, only: [:show] do
    resources :likes, only: %i[create destroy]
  end

  resources :copychecks, only: %i[new create show update index]
  resources :inquiries, only: %i[new create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i[show edit update] do
    resources :followers, only: %i[create destroy index]
    resources :followings, only: [:index]
    resources :violations, only: %i[new create]
    resources :accounts, module: 'business', only: %i[new create] do
      post :confirm, on: :collection
    end
    resource :avatar, only: [:destroy], module: 'users'
  end

  scope module: :business do
    resources :accounts, only: %i[show edit update destroy] do
      patch :confirm, on: :member
      resources :payouts, only: %i[new create]
      resources :idcards, only: %i[new create]
      resource  :extacct, only: %i[new create edit update]
    end
    resources :idcards, only: [:destroy]
    resources :bank_autocomplete, only: [:index]
    resources :branch_autocomplete, only: [:index]
  end

  resources :emailrecs, only: %i[index show]
  resource :policy, only: [:show]
  resource :userterm, only: [:show]
  resource :tokutei, only: [:show]
end

app/models/violation.rb
# frozen_string_literal: true

class Violation < ApplicationRecord
  belongs_to  :user
  validates   :user_id, uniqueness: { scope: :reporter_id, case_sensitive: true, message: "この#{Violation.model_name.human}はすでに存在します。" }
  validates   :reporter_id, presence: true, numericality: { only_integer: true }
  validates   :block, inclusion: { in: [true, false] }
  validates   :text, length: { maximum: 400 }
end

app/controllers/violations_controller.rb
# frozen_string_literal: true

class ViolationsController < ApplicationController
  before_action :unfollow, only: %i[create]

  def new
    @user = User.find(params[:user_id])
    @violation = Violation.new
  end

  def create
    @violation = Violation.new(create_params)
    if @violation.save
      redirect_to user_path(params[:user_id]), notice: "#{User.find(params[:user_id]).nickname}さんに対する違反報告を受け付けました。" and return
    else
      @user = User.find(params[:user_id])
      render :new and return
    end
  end

  private

  def create_params
    params.require(:violation).permit(:text, :block).merge(user_id: params[:user_id], reporter_id: current_user.id)
  end

  def unfollow
    target_usr = User.find(params[:user_id])
    follow = Follow.find_by(followed: target_usr, follower: current_user)
    follow.destroy if follow.present?
  end
end

app/views/violations/_errorform.html.erb
<div class="error-message">
  <ul>
    <% @violation.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/violations/new.html.erb
<% @page_title = "違反報告・ブロック" %>
<div class="page-body">
  <div class="row">
    <div class="col s12 m12 content">
      <h1>違反報告</h1>
      <%= form_with model: [@user, @violation], url: user_violations_path, local: true, method: :post, :class => 'violation-new__form' do |f| %>
        <% if @violation.errors.any? %>
          <%= render :partial => "errorform" %>
        <% end %>
        <div class="violation-new__target-user">報告対象：<%= link_to @user.nickname, user_path(@user.id) %></div>
        <%= f.check_box :block, :class => 'reset-checkbox', :as => :boolean, :required => true %>
        <%= f.label :block, 'ユーザーをブロック' %>
        <br><br>
        <%= f.label :text, '違反内容' %>
        <%= f.text_area :text, :class => 'violation-new__text', placeholder: "４００字以内", maxlength: 400 %>
        <%= f.submit "報告する", :class => "violation-new__submit btn waves-effect" %>
      <% end %>
    </div>
  </div>
</div>