config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'top#index'

  resources :top, only: [:index]
  resources :topics do
    resources :netas, only: %i[new create]
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
    resource  :headerimage, only: %i[destroy], module: 'topics'
  end

  resources :netas, only: %i[show edit update destroy] do
    resources :trades, only: %i[new create]
    resources :reviews, only: [:create]
    resources :bookmarks, only: %i[create destroy]
  end

  match '/trades/webhook' => 'trades#webhook', :via => %i[get post]

  namespace :hashtags do
    resources :netas, only: [:index]
    resources :autocomplete, only: [:index]
  end

  resources :comments, only: [:show] do
    resources :likes, only: %i[create destroy]
  end

  resources :copychecks, only: %i[new create show update index]
  resources :inquiries, only: %i[new create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i[show edit update] do
    resources :followers, only: %i[create destroy index]
    resources :followings, only: [:index]
    resources :violations, only: %i[new create]
    resources :accounts, module: 'business', only: %i[new create] do
      post :confirm, on: :collection
    end
    resource :avatar, only: [:destroy], module: 'users'
  end

  scope module: :business do
    resources :accounts, only: %i[show edit update destroy] do
      patch :confirm, on: :member
      resources :payouts, only: %i[new create]
      resources :idcards, only: %i[new create]
      resource  :extacct, only: %i[new create edit update]
    end
    resources :idcards, only: [:destroy]
    resources :bank_autocomplete, only: [:index]
    resources :branch_autocomplete, only: [:index]
  end

  resources :emailrecs, only: %i[index show]
  resource :policy, only: [:show]
  resource :userterm, only: [:show]
  resource :tokutei, only: [:show]
end

app/controllers/followers_controller.rb
# frozen_string_literal: true

class FollowersController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    if @user.followed_by(current_user.id)
      redirect_to user_path(params[:user_id]), alert: I18n.t('controller.follower.duplicate') and return
    else
      Follow.create!(followed_id: create_params[:user_id], follower_id: current_user.id)
    end

    @user.reload
  end

  def destroy
    @user = User.find(params[:user_id])
    @follow = Follow.find_by(followed_id: delete_params[:user_id], follower_id: delete_params[:id])
    if @follow.present?
      @follow.destroy!
      @user.reload
    else
      redirect_to user_path(params[:user_id]), alert: I18n.t('controller.follower.blank') and return
    end
  end

  private

  def create_params
    params.permit(:user_id)
  end

  def delete_params
    params.permit(:user_id, :id)
  end
end

app/views/followers/_follow.html.erb
<% if user.followed_by(current_user.id) %>
  <%= link_to 'フォロー中', user_follower_path(user_id: user.id, id: current_user.id), {:method => :delete, :class => "follow-button", :remote => true} %>
<% else %>
  <%= link_to 'フォローする', user_followers_path(user.id), {:method => :post, :class => "follow-button-outline", :remote => true} %>
<% end %>

app/views/followers/_follower.html.erb
<li class="follow-list collection-item">
  <%= link_to user_path(follower.id) do %>
    <div class="row follow-list">
      <div class="col s3 m3">
        <% if follower.avatar_img_url.present? %>
          <%= image_tag follower.avatar_img_url, { :class => "follow-list__avatar-img" } %>
        <% else %>
          <%= image_bundle_tag "no_user_image.png", { :class => "follow-list__avatar-img" } %>
        <% end %>
      </div>
      <div class="col s9 m9">
        <div class="follow-list__nickname"><%= follower.nickname %></div>
        <div class="follow-list__rating">
          <% if follower.average_rate == 0 %>
            <span class="js-follow-list__star" rating-data="0"></span>
          <% else %>
            <span class="js-follow-list__star" rating-data="<%= follower.average_rate %>"></span>
            <span class="follow-list__rate"><%= format("%.2f", follower.average_rate ) %></span>
          <% end %>
        </div>
        <div class="follow-list__follow-info">
          <span class="follow-list__followers">フォロワー</span>
          <span class="follow-list__followers--count"><%= follower.followers_count %></span>
        </div>
      </div>
    </div>
  <% end %>
</li>

app/views/followers/create.js.erb
$('#follows_buttons_<%= @user.id %>').html("<%= j(render partial: 'followers/follow', locals: { user: @user }) %>");

app/views/followers/destroy.js.erb
$('#follows_buttons_<%= @user.id %>').html("<%= j(render partial: 'followers/follow', locals: { user: @user }) %>");

app/views/followers/index.html.erb
<% @page_title = 'フォロワー' %>
<% breadcrumb :followed_list, @user %>
<div class="page-body">
  <div class="row">
    <div class="col s12 m9 content">
      <div class="row content-header">
        <%= render partial: "layouts/breadcrumbs" %>
      </div>
      <div class="row follow-index">
        <h1 class="following-index__title">フォロワー(<%= @user.followers_count %>)</h1>
        <% if @user.followers.present? %>
          <ul class="follow-list collection">
            <%= render partial: "followers/follower", collection: @user.followers %>
          </ul>
        <% else %>
          <p>（ユーザーはいません）</p><br><br>
        <% end %>
      </div>
    </div>
  </div>
</div>