config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'top#index'

  resources :top, only: [:index]
  resources :topics do
    resources :netas, only: %i[new create]
    resources :comments, only: %i[create destroy]
    resources :likes, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
    resource  :headerimage, only: %i[destroy], module: 'topics'
  end

  resources :netas, only: %i[show edit update destroy] do
    resources :trades, only: %i[new create]
    resources :reviews, only: [:create]
    resources :bookmarks, only: %i[create destroy]
  end

  match '/trades/webhook' => 'trades#webhook', :via => %i[get post]

  namespace :hashtags do
    resources :netas, only: [:index]
    resources :autocomplete, only: [:index]
  end

  resources :comments, only: [:show] do
    resources :likes, only: %i[create destroy]
  end

  resources :copychecks, only: %i[new create show update index]
  resources :inquiries, only: %i[new create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: %i[show edit update] do
    resources :followers, only: %i[create destroy index]
    resources :followings, only: [:index]
    resources :violations, only: %i[new create]
    resources :accounts, module: 'business', only: %i[new create] do
      post :confirm, on: :collection
    end
    resource :avatar, only: [:destroy], module: 'users'
  end

  scope module: :business do
    resources :accounts, only: %i[show edit update destroy] do
      patch :confirm, on: :member
      resources :payouts, only: %i[new create]
      resources :idcards, only: %i[new create]
      resource  :extacct, only: %i[new create edit update]
    end
    resources :idcards, only: [:destroy]
    resources :bank_autocomplete, only: [:index]
    resources :branch_autocomplete, only: [:index]
  end

  resources :emailrecs, only: %i[index show]
  resource :policy, only: [:show]
  resource :userterm, only: [:show]
  resource :tokutei, only: [:show]
end

app/models/neta.rb
# frozen_string_literal: true

class Neta < ApplicationRecord
  belongs_to  :user
  belongs_to  :topic
  counter_culture :topic, column_name: proc { |model| model.private_flag? ? nil : 'netas_count' }
  has_rich_text :content
  has_rich_text :valuecontent
  has_many :reviews, dependent: :destroy
  has_many :trades, dependent: :restrict_with_error
  has_many :pageviews, as: :pageviewable, dependent: :destroy
  has_many :bookmarks, as: :bookmarkable, dependent: :destroy
  has_many :rankings, as: :rankable, dependent: :destroy
  has_many :hashtag_netas, dependent: :destroy
  has_many :hashtags, through: :hashtag_netas
  validates :title, presence: true, length: { maximum: 35 }
  validates :private_flag, inclusion: { in: [true, false] }
  validate  :price_check
  validate  :content_check
  validate  :valuecontent_check

  def self.average_rate(netas)
    gross_count = 0
    gross_rate = 0
    if netas.present?
      netas.each do |neta|
        if neta.reviews_count != 0
          gross_rate += neta.average_rate * neta.reviews_count
          gross_count += neta.reviews_count
        end
      end
      if gross_count.zero?
        0
      else
        (gross_rate / gross_count.to_f).round(2)
      end
    else
      0
    end
  end

  def update_average_rate
    if reviews.present?
      avg = reviews.average(:rate).round(2)
      if avg.is_a? Numeric
        if update(average_rate: avg)
          [true, avg]
        else
          [false, 'error updating average_rate']
        end
      else
        [false, 'error retrieving average rate']
      end
    else
      [false, 'no reviews exist for the neta']
    end
  end

  def owner(user)
    user_id == user.id
  end

  def editable
    trades.count.zero?
  end

  def for_sale
    if price.zero?
      false
    elsif user.premium_user[0]
      if user.stripe_account.present?
        user.stripe_account.status == 'verified'
      else
        false
      end
    else
      false
    end
  end

  def public_str
    if private_flag
      '非公開'
    else
      '公開'
    end
  end

  def add_pageview(user)
    from = 1.day.ago
    to = Time.zone.now
    pageviews.find_or_create_by(user: user, created_at: from..to)
  end

  def dependents
    if reviews.present?
      true
    elsif trades.present?
      true
    elsif bookmarks.present?
      true
    else
      rankings.present?
    end
  end

  def bookmarked(user_id)
    bookmark = bookmarks.find_by(user_id: user_id)
    bookmark.present?
  end

  def save_with_hashtags(tag_array)
    if tag_array.blank?
      save
    else
      return false unless hashtag_check(tag_array)

      ActiveRecord::Base.transaction do
        clear_hashtags
        save!
        tag_array.uniq.map do |tag_name|
          unless hashtags.find_by(hashname: tag_name)
            tag = Hashtag.find_or_create_by(hashname: tag_name)
            hashtags << tag
          end
        end
      end
      true
    end
  rescue StandardError => e
    ErrorUtility.log_and_notify(exc: e, data: { 'tag_array' => tag_array })
    false
  end

  def delete_with_hashtags
    ActiveRecord::Base.transaction do
      clear_hashtags
      destroy!
    end
    true
  rescue StandardError => e
    ErrorUtility.log_and_notify(exc: e, data: { 'neta' => self, 'hashtags' => hashtags })
    false
  end

  def clear_hashtags
    # only destroy will work with counter culture
    hashtags.destroy_all if hashtags.present?
  end

  def hashtags_str
    if hashtags.present?
      tags = hashtags
      tag_array = []
      tags.each do |tag|
        tag_array.push(tag.hashname)
      end
      tag_array.join(',')
    else
      ''
    end
  end

  def self.details_from_ids(ids)
    netas = Neta.where(id: ids)
    if netas.present?
      neta_hash = {}
      netas.each do |neta|
        neta_hash.merge!({ neta.id => { 'title' => neta.title } })
      end
      neta_hash
    else
      false
    end
  end

  private

  def price_check
    if price.blank?
      errors.add(:price, I18n.t('errors.messages.blank'))
    elsif price.zero?
      true
    elsif price.negative?
      errors.add(:price, I18n.t('errors.messages.greater_than_or_equal_to', count: '0'))
    elsif price < 10
      errors.add(:price, I18n.t('errors.messages.greater_than_or_equal_to', count: '10'))
    elsif price > 10_000
      errors.add(:price, I18n.t('errors.messages.less_than_or_equal_to', count: '10000'))
    end
  end

  def content_check
    errors.add(:content, I18n.t('errors.messages.blank')) if content.body.blank?
    errors.add(:content, I18n.t('errors.messages.too_long', count: '1200')) if content.to_plain_text.squish.length > 1200
    # Need attachment checks. Below does not work because at this point blob is not attached..
    # self.content.embeds.blobs.each do |blob|
    #   if blob.byte_size.to_i > 10.megabytes
    #     errors.add(:content, " size must be smaller than 10MB")
    #   end
    # end
  end

  def valuecontent_check
    if price != 0
      errors.add(:valuecontent, I18n.t('errors.messages.blank')) if valuecontent.body.blank?
      errors.add(:valuecontent, I18n.t('errors.messages.too_long', count: '1200')) if valuecontent.to_plain_text.squish.length > 1200
      # Need attachment checks. Below does not work because at this point blob is not attached..
      # self.valuecontent.embeds.blobs.each do |blob|
      #   if blob.byte_size.to_i > 10.megabytes
      #     errors.add(:valuecontent, " size must be smaller than 10MB")
      #   end
      # end
    elsif valuecontent.body.present?
      errors.add(:valuecontent, I18n.t('errors.messages.not_free'))
    end
  end

  def hashtag_check(tag_array)
    if tag_array.present?
      if tag_array.size > 10
        errors.add(:hashtags, I18n.t('errors.messages.attach_too_many', attach_limit: '10'))
        false
      else
        true
      end
    else
      true
    end
  end
end

app/controllers/hashtags/netas_controller.rb
# frozen_string_literal: true

class Hashtags::NetasController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    hashname = params[:keyword]
    @tag = Hashtag.find_or_initialize_by(hashname: hashname)
    if @tag.persisted?
      @netas = @tag.netas.includes(:user).where(private_flag: false).order('average_rate DESC')
      @tag.add_hit(current_user) if user_signed_in?
    end
  end
end

app/controllers/netas_controller.rb
# frozen_string_literal: true

class NetasController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show]

  def new
    @topic = Topic.find(params[:topic_id])
    @neta = @topic.netas.new
    @qualified = current_user.premium_qualified
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @neta = @topic.netas.new(create_params)
    if @neta.save_with_hashtags(tag_array)
      redirect_to neta_path(@neta.id), notice: I18n.t('controller.neta.created') and return
    else
      render :new and return
    end
  end

  def show
    @neta = Neta.find(params[:id])
    get_owner
    if @neta.private_flag && !@owner
      @message = I18n.t('controller.neta.private')
    else
      get_reviews
      add_pageview
      get_trades
      @for_sale = @neta.for_sale
    end
  end

  def edit
    @neta = Neta.find(params[:id])
    redirect_to neta_path(params[:id]), alert: I18n.t('controller.general.no_access') and return unless @neta.owner(current_user)
    redirect_to neta_path(params[:id]), alert: I18n.t('controller.neta.dependency') and return unless @neta.editable

    @qualified = current_user.premium_qualified
    @current_tags = @neta.hashtags_str
  end

  def update
    @neta = Neta.find(params[:id])
    @neta.assign_attributes(update_params)
    if @neta.save_with_hashtags(tag_array)
      redirect_to neta_path(@neta.id), notice: I18n.t('controller.neta.updated') and return
    else
      @qualified = current_user.premium_qualified
      @current_tags = @neta.hashtags_str
      render :edit and return
    end
  end

  def destroy
    @neta = Neta.includes(:trades, :bookmarks, :reviews, :pageviews, :rankings, :hashtag_netas).find(params[:id])
    deleteable = delete_check
    if deleteable[0]
      topic_id = @neta.topic_id
      if @neta.delete_with_hashtags
        redirect_to topic_path(topic_id), notice: I18n.t('controller.neta.deleted') and return
      else
        redirect_to neta_path(params[:id]), alert: I18n.t('controller.general.no_access') and return
      end
    else
      redirect_to neta_path(params[:id]), alert: deleteable[1] and return
    end
  end

  private

  def create_params
    params.require(:neta).permit(:title, :content, :valuecontent, :price, :private_flag).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:neta).permit(:title, :content, :valuecontent, :price, :private_flag)
  end

  def tag_params
    params.require(:neta).permit(:tags)
  end

  def tag_array
    if tag_params['tags'].present?
      tag_str = tag_params['tags']
      tag_str.split(/,/)
    else
      []
    end
  end

  def delete_check
    if @neta.owner(current_user)
      if @neta.dependents
        [false, I18n.t('controller.neta.undeleteable')]
      else
        [true, nil]
      end
    else
      [false, I18n.t('controller.general.no_access')]
    end
  end

  def get_owner
    @owner = if user_signed_in?
               @neta.owner(current_user)
             else
               false
             end
  end

  def get_reviews
    @reviews = @neta.reviews.includes(:user).order('created_at DESC')
    if user_signed_in?
      @my_review = @reviews.find_by(user_id: current_user.id)
      @new_review = Review.new if @my_review.blank?
    end
  end

  def add_pageview
    @neta.add_pageview(current_user) if user_signed_in?
  end

  def get_trades
    @my_trade = @neta.trades.find_by(buyer_id: current_user.id) if user_signed_in?
  end
end

app/views/netas/_errorform.html.erb
<div class="error-message">
  <ul>
    <% @neta.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>

app/views/netas/_neta.html.erb
<li class="neta-index collection-item">
  <%= link_to neta_path(neta.id) do %>
    <div class="neta-index__title"><%= neta.title %></div>
    <% if neta.average_rate == "-" %>
      <span class="js-neta-index__star" rating-data="0"></span>
    <% else %>
      <span class="js-neta-index__star" rating-data="<%= neta.average_rate %>"></span>
      <span class="neta-index__star-count"><%= format("%.2f", neta.average_rate) %></span>
    <% end %>
    <i class="review--large material-icons">chat_bubble_outline</i>
    <span class="review__count"><%= neta.reviews_count %></span>
    <div class="neta-index__footer">
      <%= link_to user_path(neta.user_id) do %>
        <% if neta.user.avatar_img_url.present? %>
          <%= image_tag neta.user.avatar_img_url, {:class => "neta-index__author-image"} %>
        <% else %>
          <%= image_bundle_tag "no_user_image.png", {:class => "neta-index__author-image"} %>
        <% end %>
      <% end %>
      <span class="neta-index__footer-text">
        <%= neta.user.nickname %>&nbsp;&nbsp;
        <%= neta.created_at.to_s(:human) %>&nbsp;&nbsp;
      </span>
    </div>
  <% end %>
</li>

app/views/netas/_netaform.html.erb
<%= javascript_bundle_tag 'hashtag-entry' %>
<%= javascript_bundle_tag 'neta' %>
<div class="neta-form__title">
  <%= form.label :title, "タイトル／キャッチフレーズ", :class => "neta-form__title-label" %>
  <%= form.text_field :title, :value => @neta.title, :class => 'neta-form__title-text', :minlength => '5', :maxlength => '35' %>
</div>
<div class="neta-form__content">
  <%= form.label :content, "本文", :class => "neta-form__content-label" %>
  <%= form.rich_text_area :content, :value => @neta.content, :class => "neta-form__content-textarea" , :placeholder => '８００字以内' %>
</div>
<% if @qualified %>
<div class="neta-form__valuecontent">
  <%= form.label :value_content, "有料部分", :class => "neta-form__valuecontent-label" %>
  <%= form.rich_text_area :valuecontent, :value => @neta.valuecontent, :class => "neta-form__valuecontent-textarea", :placeholder => '有料部分（８００字以内）' %>
</div>
<% end %>
<div class="neta-form__hashtags">
  <%= form.text_field :tags, :value => @current_tags, :autocomplete => 'off', :id => 'js-tag_post_field' %>
</div>
<div class="neta-form__price">
  <%= form.label :price, "価格", :class => 'neta-form__price-label' %><br>
  <% if @qualified %>
    <%= form.number_field :price, :value => @neta.price, :class => 'neta-form__price-field--active', min: 0, step: 10 %>&nbsp;&nbsp;円
  <% else %>
    <%= form.number_field :price, :value => @neta.price, :class => 'neta-form__price-field--inactive', :readonly => true %>&nbsp;&nbsp;<span class="neta-form__price-invalid">円</span>
    <div class="neta-form__price-invalid">（有料投稿はビジネスアカウント登録が必要です）</div>
  <% end %>
</div>
<div class="neta-form__private">
  <%= form.label :private_flag, "公開／非公開", :class => 'neta-form__private-label' %>
  <%= form.select :private_flag, [['公開', false], ['非公開', true]], { include_blank: false, selected: @neta.private_flag }, { class: "browser-default", :id => "neta-form__private-flag" } %>
</div>

app/views/netas/edit.html.erb
<% @page_title = "ネタ編集" %>
<% breadcrumb :edit_neta, @neta %>
<div class="page-body">
  <div class="row">
    <div class="col s12 m12 content">
      <div class="row content-header">
        <%= render partial: "layouts/breadcrumbs" %>
      </div>
      <div class="row neta-edit">
        <h1>ネタ（編集）</h1>
        <%= form_with model: @neta, local: true, method: :patch, :class => "neta-edit__form" do |form| %>
          <% if @neta.errors.any? %>
            <%= render :partial => "errorform" %>
          <% end %>
          <%= render :partial => "netaform", locals: { form: form } %>
          <%= button_tag :type => "submit", data: {disable_with: '保存中...'}, :class => "neta-edit__update btn waves-effect" do %>
            <i class="material-icons left">refresh</i>更新
          <% end %>
          <%= link_to neta_path(@neta.id), {:method => :delete, :class => 'neta-edit__delete btn waves-effect', data: { confirm: "本当に削除しますか？" }} do %>
            <i class="material-icons left">delete</i>削除
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/netas/hashtags.html.erb
<%= javascript_bundle_tag 'hashtag' %>
<% @page_title = "#"+@tag.hashname %>
<% breadcrumb :hashtag, @tag %>
<div class="page-body-container">
  <%= breadcrumbs separator: "  &rsaquo;  ", :class => "breadcrumbs custom" %>
  <%= form_with url: netas_hashtags_path("search"), local: true, method: :get, :id => 'hashtag_search_form' do |f| %>
    <%= f.text_field :keyword, :value => params[:keyword], :autocomplete => 'off', :id => "tag_search_field" %>
    <%= f.hidden_field :search_form, :value => "true" %>
    <%= f.submit '検索', class: "btn btn-primary withripple custom", :name => nil %>
  <% end %>
  <div class="row">
    <div class="col s12 m9 show">
      <% unless @netas %>
        <p> (ネタの投稿はまだありません) </p><br>
      <% else %>
        <h1>#<%= @tag.hashname %></h1>
        <ul class="collection">
          <%= render partial: "netas/neta", :collection => @netas %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/netas/new.html.erb
<% @page_title = "新規ネタ" %>
<% breadcrumb :new_neta, @topic %>
<div class="page-body">
  <div class="row">
    <div class="col s12 m12 content">
      <div class="row content-header">
        <%= render partial: "layouts/breadcrumbs" %>
      </div>
      <div class="row neta-new">
        <h1>新規ネタ</h1>
        <%= form_with model: [@topic, @neta], local: true, method: :post do |form| %>
          <% if @neta.errors.any? %>
            <%= render :partial => "errorform" %>
          <% end %>
          <%= render :partial => "netaform", locals: { form: form } %>
          <%= button_tag :type => "submit", data: {disable_with: '保存中...'}, :class => "neta-new__submit btn waves-effect" do %>
            <i class="neta-new__submit material-icons left">create</i>投稿
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/netas/show.html.erb
<% @page_title = @neta.title %>
<% @page_description = @neta.content.to_plain_text.squish.truncate(120) %>
<%= content_for(:ogp_article) do %>
  <meta property="og:type" content="article">
  <meta property="og:image" content="<%= ENV['HOST_URL'] + asset_bundle_path("images/logo-color-1.png") %>">
<% end %>
<% breadcrumb :show_neta, @neta %>
<div class="page-body">
  <div class="row">
    <div class="col s12 m12 content">
      <% if @neta.private_flag && !@owner %>
        <%= @message %>
      <% else %>
        <div class="row content-header">
          <%= render partial: "layouts/breadcrumbs" %>
        </div>
        <div class="row neta-show">
          <h1 class="neta-show__title"><%= @neta.title %></h1>
          <div class="neta-show__text--free"><%= @neta.content %></div>
          <div class="neta-show__value-content">
            <% if @neta.price != 0 %>
              <% if ( @owner || @my_trade.present? ) %>
                <p class="neta-show__text-divider">---------  以下、有料部分   ---------</p>
                <% if @neta.valuecontent.present? %>
                  <div class="neta-show__text--value"><%= @neta.valuecontent %></div>
                <% end %>
                <% if @my_trade.present? %>
                  <span class="neta-show__price--active"><%= number_to_currency(@my_trade.price, locale: 'ja') %>で購入済み</span>
                <% else %>
                  <span class="neta-show__price--active">価格：<%= number_to_currency(@neta.price, locale: 'ja') %></span>
                <% end %>
              <% else %>
                <% if @for_sale %>
                  <div class="neta-show__text-divider">--------  これより先は有料コンテンツです  --------</div>
                  <span class="neta-show__price--active">価格：<%= number_to_currency(@neta.price, locale: 'ja') %></span>&nbsp;&nbsp;
                  <%= link_to "購入", new_neta_trade_path(@neta.id), {:class => 'neta-show__purchase btn waves-effect' } %>
                  <span class="neta-show__bookmark">
                    <% if user_signed_in? %>
                      <span id="bookmark_buttons_<%= @neta.class.name.downcase %>_<%= @neta.id %>">
                        <%= render partial: 'bookmarks/bookmark', locals: { bookmarkable: @neta } %>
                      </span>
                    <% else %>
                      <i class="bookmark-large material-icons">bookmark_border</i>
                    <% end %>
                  </span>
                <% else %>
                  <p class="neta-show__text-divider">--------  現在は販売されておりません  --------</p>
                  <span class="neta-show__price--inactive"><%= number_to_currency(@neta.price, locale: 'ja') %></span>
                  <div class="btn btn-primary withripple custom inactive">購入</div>
                <% end %>
              <% end %>
            <% end %>
          </div>

          <% @neta.hashtags.each do |tag| %>
            <div class="neta-show__hashtag"><%= link_to "#"+tag.hashname, "/hashtags/netas?keyword=#{tag.hashname}" %></div>
          <% end %>

          <% if @owner %>
            <div class="neta-show__edit-link"><%= link_to "編集", edit_neta_path(@neta.id) %></div>
          <% end %>
          <div class="neta-show__footer">
            <%= link_to user_path(@neta.user_id) do %>
              <% if @neta.user.avatar_img_url.present? %>
                <%= image_tag @neta.user.avatar_img_url, {:class => "neta-show__author-image"} %>
              <% else %>
                <%= image_bundle_tag "no_user_image.png", {:class => "neta-show__author-image"} %>
              <% end %>
            <% end %>
            <span class="neta-show__footer-text">
              <%= @neta.user.nickname %>&nbsp;&nbsp;
              <%= @neta.created_at.to_s(:human) %>&nbsp;&nbsp;
            </span>
          </div>
        </div>  
        <div class="row neta-show__review">
          <% if !@owner && @new_review.present? %>
            <% unless ( @for_sale && @my_trade.blank? ) %>
              <ul class="neta-show__review-index collection">
                <%= render partial: "reviews/reviewform", locals: { neta: @neta, new_review: @new_review } %>
              </ul>
            <% end %>
          <% else %>
            <h2>レビュー(<%= @reviews.count %>件)</h2>
            <% if @reviews.present? %>
              <ul class="neta-show__review-index collection">
                <%= render partial: "reviews/review", collection: @reviews %>
              </ul>
            <% else %>
              <p class="neta-show__review-nodata"> (レビューはありません) </p>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>